Not all repos have master as their default branch.
Many repositories have switched from using 'master' to a less
potentially offensive name like 'main' for their primary branch.

* Update `git-prune-branches` to not assume the default branch is named
  master
* Add `git-remote-default-branch` to make it easy to find the default
  branch name.

diff --git a/bin/git-prune-branches b/bin/git-prune-branches
--- a/bin/git-prune-branches
+++ b/bin/git-prune-branches
@@ -14,7 +14,13 @@
 # License: MIT
 # Original source: https://github.com/jut-io/git-scripts/blob/master/bin/git-prune-branches
 
-merged=$(git branch --no-color --merged master | grep -v master | sed 's/\*/ /')
+PRIMARY_BRANCH=$(git remote show origin | awk '/HEAD branch/ {print $3}')
+if [[ -z "$PRIMARY_BRANCH" ]]; then
+  echo "Could not determine primary branch"
+  exit 13
+fi
+
+merged=$(git branch --no-color --merged "$PRIMARY_BRANCH" | grep -v "$PRIMARY_BRANCH" | sed 's/\*/ /')
 
 if [ ! -z "$merged" ] ; then
   echo "Deleting the following merged branches:"
